services:
  - type: web
    name: artsyshop
    runtime: node
    plan: free
    region: singapore
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NEXT_PUBLIC_SUPABASE_URL
        value: https://fqubsupqkorxfgohartk.supabase.co
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        value: sb_publishable_fCYxAzMOcCTisJNWjC-2NA_VDR-IVbR
      - key: NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY
        value: sb_publishable_fCYxAzMOcCTisJNWjC-2NA_VDR-IVbR
      - key: NEXT_PUBLIC_ADMIN_EMAIL
        value: mardionjrcordetafuerte@gmail.com
      - key: NEXT_PUBLIC_ADMIN_PASSWORD
        value: january2026
